[api]
# API基础地址
base_url = http://localhost:17026
# 检测间隔（秒）
interval = 3

[jianying]
# 剪映程序路径
app_path = C:\Program Files\VideoFusion\VideoFusion.exe
# 剪映草稿目录
drafts_path = C:\Users\xuwenzhen\Videos\JianyingPro\User Data\Projects\com.lveditor.draft
# 剪映视频导出目录
exports_path = C:\Users\xuwenzhen\Downloads\video

[upload]
# 上传方式，支持：api / oss / cos
storage = oss
# 上传成品视频存储key前缀，最终存储在： {video_key_prefix}/{video_file_name}
video_key_prefix = video/

[oss]
# 阿里云OSS配置
bucket_name = your-bucket-name
access_key_id = YOUR_ACCESS_KEY
access_key_secret = YOUR_SECRET_KEY
endpoint = oss-cn-hangzhou.aliyuncs.com
region = cn-hangzhou

[cos]
# 腾讯云COS配置
bucket_name = your-bucket-name-1234567890
secret_id = your-secret-id
secret_key = your-secret-key
region = ap-beijing

